* Idea:
Losing your place in the changing world or changing and loosing your place in the world?

ex soldier?


VR-MMORPG full dive thrauma, recovering from living in digital??
dead friends, frontline thrauma, lost contact, not knowing irl names
therapy group of post-dive recovery?

bootleg fulldive gear to return to that world, flashbacks, dreams of the virt;

Finding peace in being a loner
going back lowk kills you, physically and mentally


fog\smog world? lots of heavy weather \ pollution?

re-listening old messages from people?

story-first game with intriguing characters, setting of mystery and good writing (i will try)
big on ambience and tactility of the world

physical movement is slow, hard to maneuver (weak body)
most of movement is done in digital


living a life after being someone.



theme of losing connection

** Matching music:
Bones 	by Low Roar, Jofriour Akadottir
Eld		by Jay Ragsdale


** Draft:
possbile protagonist name:
John Nmb. Stratus  (Nimbostatus)   or..hear me out.. Storman


Corporation behind it all?


old colleagues gone? no home,
living in car or van\truck out in wild i guess, survivalist shit ???

virtual spaces

* Plot attempts

** Number one, zero swordsman

